### ISSUE TITLE
Logo is missing

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythiaCookbooks/cmip6-cookbook#22]
On this page https://cookbooks.projectpythia.org/cmip6-cookbook/README.html
the logo seems to be missing

**Comment by r-ford** [comment]
[This image](https://cookbooks.projectpythia.org/cmip6-cookbook/_images/cmip6-logo.webp)? It shows up fine on my screen.

**Comment by brian-rose** [comment]
Weird, ok, it shows up fine now. I'll chalk that up to a temporary browser glitch. Closing.
